{% set name = "eventlet" %}
{% set version = "0.40.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 290852db0065d78cec17a821b78c8a51cafb820a792796a354592ae4d5fceeb0

build:
  number: 0
  skip: True  # [py<39]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - python
    - pip
    - hatch-vcs >=0.3
    - hatchling >=1.12.2
  run:
    - python
      # Upstream not require max pin, but geenlet quite unstable dependency and would be good have a max pin
    - greenlet >=1.0
    - dnspython >=1.15.0
    # https://github.com/eventlet/eventlet/blob/0.39.0/eventlet/green/OpenSSL/crypto.py#L1
    - pyopenssl

# Mass failing testst due to greenlet FdListener('read', -1, …)
#================================================================
# $SRC_DIR/tests/__init__.py:245: AssertionError: Readers: Listener FdListener('read', 
# -1, <function select.<locals>.on_read at 0x106cdf740>, <built-in method throw of greenlet.greenlet 
# object at 0x103a0e240>) for greenlet <greenlet.greenlet object at 0x103a0e240 (otid=0x1039bb1b0) 
# current active started main> with run callback None (1) Writers:  (0)

# E   AssertionError: Readers: Listener FdListener('read', -1, <function select.<locals>.on_read at 0x10870e840>, <built-in method throw of greenlet.greenlet object at 0x10468cb80>) for greenlet <greenlet.greenlet object at 0x10468cb80 (otid=0x10463e5b0) current active started main> with run callback None (1) Writers:  (0)
# ___ TestWebSocketWithCompression.test_accept_deflate_ext_context_takeover_13 ___
# tests/wsgi_test.py:245: in tearDown
#     super().tearDown()
# tests/__init__.py:194: in tearDown
#     verify_hub_empty()
# tests/__init__.py:245: in verify_hub_empty
#     assert num_readers == 0 and num_writers == 0, \
{% set SKIP_TEST_FILES = [
    "tests/mysqldb_test.py",
] %}

#FAILED tests/backdoor_test.py::BackdoorTest::test_server_on_unix_socket - PermissionError: 
# [Errno 1] Operation not permitted: '/tmp/eventlet_backdoor_test.socket'
{% set SKIP_TEST_LINUX = [
    "test_server_on_unix_socket",
] %}

test:
  source_files:
    - tests
  imports:
    - eventlet
    - eventlet._version
    - eventlet.asyncio
    - eventlet.corolocal
    - eventlet.dagpool
    - eventlet.event
    - eventlet.green
    - eventlet.greenio
    - eventlet.greenthread
    - eventlet.hubs
    - eventlet.lock
    - eventlet.patcher
    - eventlet.pools
    - eventlet.semaphore
    - eventlet.support
    - eventlet.timeout
    - eventlet.tpool
    - eventlet.websocket
    - eventlet.zipkin
  requires:
    - pip
    - pytest
    - pyopenssl
    - aiohttp
    - pyzmq 21.*    # [py==39]
    - pyzmq 27.*    # [py>=310]
    - psycopg2 2.8.*     # [py==39]
    - psycopg2 2.9.*     # [py>=310]
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert version('{{ name }}') == '{{ version }}'"
    - export EVENTLET_HUB=epolls  # [linux]
    - pytest -ra -v --tb=short tests {% for file in SKIP_TEST_FILES %} --ignore={{ file }}{% endfor %} -v -k "not slow and not ({{ SKIP_TEST_LINUX | join(' or ') }})"  # [linux]

about:
  home: https://github.com/eventlet/eventlet
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Highly concurrent networking library
  description: |
    Eventlet is a concurrent networking library for Python that allows you to 
    change how you run your code, not how you write it.
    It uses epoll or libevent for highly scalable non-blocking I/O. 
    Coroutines ensure that the developer uses a blocking style of programming 
    that is similar to threading, but provide the benefits of non-blocking I/O. 
    The event dispatch is implicit, which means you can easily use Eventlet from the 
    Python interpreter, or as a small part of a larger application.
  dev_url: https://github.com/eventlet/eventlet
  doc_url: https://eventlet.readthedocs.io

extra:
  recipe-maintainers:
    - synapticarbors
    - anguslees
    - pmlandwehr
