{% set name = "eventlet" %}
{% set version = "0.25.2" %}
{% set bundle = "tar.gz" %}
{% set hash = "4c8ab42c51bff55204fef43cff32616558bedbc7538d876bb6a96ce820c7f9ed" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: {{ hash }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python
    - pip

  run:
    - python
    - greenlet >=0.3
    - enum34  # [py<34]
    - dnspython >=1.15.0
    - monotonic >=1.4
    - six >=1.10.0
    - pyopenssl

test:
  imports:
    - eventlet
    - eventlet.green
    - eventlet.green.OpenSSL
    - eventlet.green.http  # [py3k]
    - eventlet.green.urllib
    - eventlet.greenio
    - eventlet.hubs
    - eventlet.support

about:
  home: http://eventlet.net
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Highly concurrent networking library
  dev_url: https://github.com/eventlet/eventlet
  doc_url: http://eventlet.net

extra:
  recipe-maintainers:
    - synapticarbors
    - anguslees
    - pmlandwehr
