{% set name = "eventlet" %}
{% set version = "0.40.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 290852db0065d78cec17a821b78c8a51cafb820a792796a354592ae4d5fceeb0

build:
  number: 0
  skip: True  # [py<39]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - python
    - pip
    - hatch-vcs >=0.3
    - hatchling >=1.12.2
  run:
    - python
    - greenlet >=1.0
    - dnspython >=1.15.0

test:
  source_files:
    - tests
  imports:
    - eventlet
    - eventlet._version
    - eventlet.asyncio
    - eventlet.corolocal
    - eventlet.dagpool
    - eventlet.event
    - eventlet.green
    - eventlet.greenio
    - eventlet.greenthread
    - eventlet.hubs
    - eventlet.lock
    - eventlet.patcher
    - eventlet.pools
    - eventlet.semaphore
    - eventlet.support
    - eventlet.timeout
    - eventlet.tpool
    - eventlet.websocket
    - eventlet.zipkin
  requires:
    - pip
    - pytest
    - aiohttp                   # [py>=39]
    - pyopenssl
    - pyzmq 21.*                # [py==39]
    - pyzmq 27.*                # [py>=310]
    - mysqlclient 2.0.3         # [py==39]
    - mysqlclient 2.2.*         # [py>=310]
    - psycopg2 2.8.*            # [py==39]
    - psycopg2 2.9.*            # [py>=310]
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert version('{{ name }}') == '{{ version }}'"
    - pytest -ra -v --tb=line tests

about:
  home: https://github.com/eventlet/eventlet
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Highly concurrent networking library
  dev_url: https://github.com/eventlet/eventlet
  doc_url: https://eventlet.readthedocs.io

extra:
  recipe-maintainers:
    - synapticarbors
    - anguslees
    - pmlandwehr
