travis:
  secure:
    BINSTAR_TOKEN: GB5ktuYqcCaDRLdBPe4f5ckJeBKP9MsnWHxz6dGOBomJFp3uMRQN+nrw6O+QtovsvPld01FJc4Ki9JHVAilHAosy6ML6Yh+MawuiEzZt9o4wKiGyCvYLoJvufKRbtOhqcCpv683LwwGy8LJ3seY0ob5cRZ2xnSHW17OlVi9QTmX/Ke8lkHfw1aBWAr261diHJAPn/qMAqXT81FPdVOZeQDV+HEyse37TeELMbjncOW+TwwXV8GsO29iC2daW36ReTUb5NrHU77ciZcsUMOOAg1MPoQZvvoGyXxaDMoMR6X8AFnCa5k37DM813ofuAX5SGP0ZttbCw2wR3gSv0PF6WffTJrSjKJlcS6YgqWdj5uC0kdleq97V1CDX4VoShorgsP2m63X281KznVuAHgADCLQcND8ad3d68RX3FffaDEnUWCUZ7rM/fLPRQWqmUvTA4ahA8GnacLUP1JGn6hoSnO0yO7tdENuQnPSLW9fbt+wlmbNde3qRcblYUiELQDjzF7TttwBYYK0ETYyhYTIC1usVWp8UaqhwFrFO7kT3nZWuv/Pb9G4VpDn/FZJgRPLyRL1zvbFLDv28cnOV1xQ9WfFdufETmXTnPqzEr77hRig0i47uY7cT5iFjIPyqYmcHRLWiHIS7NzneS0QaGEUhqcP3aRvPPFlMmmtWSClsFnA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
