appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: Ia0tvdHNPw6JYC+mcOT3de3+e1rVz7hZSWHT2NLJaeCzrm6j9DUcD6KIULjfTW68+9P6slcaBqf/EO29wS2JhRZGR5626ks5/PiJRr219s/4GV9YVI064u1VX3qa0XCPjCx9TbzRfEATb8az3CpfTaqhj6k/8wYCAKKa7HJwUoDeCpEMitl1UfUBeili3BxOXgS07T8DBMh0CLzwcwRv2ol473GSL47QqseRmDIcINCSK7dMBeA2NffmpLfg4w85QZMSnqqmdJlQ/Cp+ttLa7RaoHLs/Sa82OLEKe9sghguhViRxQ/jiiYflPLYJYviTevQMconP2QQD9m4ppoLw03s3PWY9yauXlkF2uq8qvIJ6olxu5Jsq1A9Yh3tJHjqw3DhjefgKkmwLNu/goXTbqICebGSSAUJbnCY1OFw0BzgqJy4S82smh1kzqD/VJA/zlbtAbUZIguVuVcYLKfVjIQkWYLpK1J4rAej/oU38wememv3soIkx2Em/0G9+kpEukHTXo2dOZBaAsi0ux5ExGu2kofITlT0irj1cB16nquCFtyZ51+fbVyRiblH7oFHqDz2fcxi+xAxjmhRHl0XxCG9MyiW/f2Mu5mIgjbdfQDz1/fgBXDNnexp8u+6XwbGCeUAoQLtLmjsmeAKJK7+43XngZWikLWFVdEY2M8fRYGE=}
provider:
  win: azure
conda_forge_output_validation: true
